version: "3.8"
services:
    web:
        image: nginx:1.19.2-alpine
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./src:/var/www/html
            - ./images/dev/config/default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
    php:
        build:
            context: images/dev/php
        restart: unless-stopped
        volumes:
            - ./src:/var/www/html
        links:
            - postgres
        environment:
            DB_URI: pgsql://phpuser:phppassword@postgres:5432/postgres-dev
            JWK_URI: https://mmsm.eu.auth0.com/.well-known/jwks.json
    postgres:
        image: postgres
        restart: unless-stopped
        environment:
            POSTGRES_USER: phpuser
            POSTGRES_PASSWORD: phppassword
            POSTGRES_DB: postgres-dev
    adminer:
        image: adminer
        restart: unless-stopped
        ports:
            - 8080:8080
